### ISSUE TITLE
Issue with Time based up scaling 

### ISSUE THREAD

**Issue by bdre-bda** [atlassian/themis#19]
Here are my settings. 
![image](https://cloud.githubusercontent.com/assets/13850135/18946011/a9b186f6-864a-11e6-8bea-73ef6e87a3aa.png)

Here is the history.
![image](https://cloud.githubusercontent.com/assets/13850135/18946042/dac1ba4a-864a-11e6-8a83-0917d7eda3c4.png)

As it can be seen in settings, I am trying to upscale my cluster by the number of minimum nodes (time based) which is 2, but it can be seen in the history that it up scaled the cluster by only 1 node. Which means that time.based.minimum.nodes is taking the default value of 1. I am pretty sure that not matching the time regex in json is not an issue because it has matched just before, while I was performing a down scaling operation. Please let me know if this is  a valid issue or if there's something on my side, which I'm doing wrong.

**Comment by whummer** [comment]
Hi, thanks for reporting. I believe the time-based scaling configuration must be a strictly valid JSON string, using double quotes (`"`) instead of single quotes (`'`). Can you please give that a try?

Also, is there anything "suspicious" (ERROR messages, stack traces) in the terminal log output or the `themis.log` file?

We're aware that the current configuration interface is a bit clunky, we're aiming to improve it and have a more easy to use configuration interface in the near future.

**Comment by sriharshaboda** [comment]
Hi, thanks for the quick response. The double quotes did the trick for me. Shouldn't have missed them in the first place. 
Another question unrelated to this: What is the difference between tasknodes.running & tasknodes.active? Does active consider any active EMR steps running on the cluster? 
Thanks again.

**Comment by whummer** [comment]
Great, I'm glad that helped. `tasknodes.running` is about the EC2 state of the machines (the value returns `true` if all nodes have been started in terms of their EC2 VMs), whereas `tasknodes.active` is used to indicate the state of the Presto Java process running on the nodes, assuming you are using Presto in your cluster (the value returns `true` if all nodes are up and running and ready to receive requests from the master node). We'll add some more documentation to the README, to make this clearer.
